# Generated by Django 2.2.7 on 2019-11-07 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parsapp.Info'),
        ),
    ]
