# Generated by Django 2.2.7 on 2019-11-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsapp', '0003_auto_20191107_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Площадь дома'),
        ),
        migrations.AlterField(
            model_name='info',
            name='danger',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Аварийный'),
        ),
        migrations.AlterField(
            model_name='info',
            name='fond',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фонд кап ремонта'),
        ),
        migrations.AlterField(
            model_name='info',
            name='house_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип дома'),
        ),
        migrations.AlterField(
            model_name='info',
            name='last_changes',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Последние изменения анкеты'),
        ),
        migrations.AlterField(
            model_name='info',
            name='serial',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='info',
            name='stages',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Кол-во этажей'),
        ),
        migrations.AlterField(
            model_name='info',
            name='wall_mat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Материал стен'),
        ),
        migrations.AlterField(
            model_name='info',
            name='wall_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип перекрытия'),
        ),
        migrations.AlterField(
            model_name='info',
            name='year_build',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Год постройки'),
        ),
        migrations.AlterField(
            model_name='info',
            name='year_exp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Год ввода в эксплуатацию'),
        ),
        migrations.AlterField(
            model_name='info',
            name='year_exp1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Год ввода в экспулатацию'),
        ),
    ]
