# Generated by Django 2.2.7 on 2019-11-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsapp', '0004_auto_20191107_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='stages',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во этажей'),
        ),
    ]
